apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- $dockerConfigJSON := index .Values.imagePullSecrets ".dockerconfigjson" }}
data:
  .dockerconfigjson: {{ $dockerConfigJSON | quote }}
type: kubernetes.io/dockerconfigjson
