apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  # Replace with base64 of ~/.docker/config.json after docker login to ghcr.io.
  .dockerconfigjson: ewogICJhdXRocyI6IAogIHsKICAgICAgICAgICJnaGNyLmlvIjoKICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWjJsbllXZHlhV2M2WjJod1gzTTBTRnBCY0daNWFXcHlPRXhWUWs1MlVYSTJWbVpJVFRnMk4yRnhValJXZFRGaGVnbz0iCiAgICAgICAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
